---
name: build
on:
  push:
    branches: [MMBase-1_9]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #container: mmbase/build:1
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.12.1
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          server-id: 'ossrh'
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: ./build-all.sh
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()    # run this step even if previous step failed
        with:
          files: '**/target/surefire-reports/TEST-*.xml'    # Path to test
      - uses: codecov/codecov-action@v4
        if: github.ref == 'refs/heads/MMBase-1_9'
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)

